### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by L1cardo** [exyte/ActivityIndicatorView#10]
Xcode Version 12.0 (12A7209)
![image](https://user-images.githubusercontent.com/33802186/94087166-ac940d00-fe3f-11ea-9f7f-275615c04473.png)

**Comment by f3dm76** [comment]
@L1cardo Compiles without errors for me on Xcode 12.0.1, could you please give it a try?

**Comment by f3dm76** [comment]
I am closing this one, since there's been an Xcode update since this issue was opened, @L1cardo please open another one if you are still having problems
