### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by L1cardo** [exyte/ActivityIndicatorView#13]
Can not this run on tvOS?

**Comment by f3dm76** [comment]
@L1cardo It can, please try it out

**Comment by L1cardo** [comment]
> @L1cardo It can, please try it out

That is the problem, I can not even try!
![image](https://user-images.githubusercontent.com/33802186/95184597-27730580-07fa-11eb-98a4-aecc8d4c2066.jpeg)

**Comment by f3dm76** [comment]
Could you please try to specify exactly what you mean, cause I thought we were talking about cocoapods. Added the required line, give it a go, please.

**Comment by L1cardo** [comment]
I was talking about swift package manager, I do not use cocoapods in my project￼￼.
Since there is no tvOS in package file， I can not test.

**Comment by f3dm76** [comment]
.tvOS(.v13) line should be there now, do I need to do anything else for it to work for you?

**Comment by f3dm76** [comment]
Hey @L1cardo, did my change to package file help with your tvOS launch? Please let me know if I can help you further with this.

**Comment by L1cardo** [comment]
> Hey @L1cardo, did my change to package file help with your tvOS launch? Please let me know if I can help you further with this.

I am really busy and did not have time to test the package.
I will test it tonight and let you know ASAP.
