### ISSUE TITLE
Incompatible with NavigationView

### ISSUE THREAD

**Issue by feveral** [exyte/ActivityIndicatorView#15]
If I put ActivityIndicatorView inside NavigationView,
it would have strange behavior,
repeatedly move from top left to center.

```swift
NavigationView {
    ActivityIndicatorView(isVisible: .constant(true), type: .arcs)
        .frame(width: 70, height: 70, alignment: .center)
}
```

![output](https://user-images.githubusercontent.com/19822513/104848153-a52cce00-591e-11eb-9ef3-4930a2487c70.gif)

**Comment by f3dm76** [comment]
Hey @feveral , just writing to let you know we didn't forget about you, but unfortunately we do not have time to address the issue right now. We will work on it as soon as we can, and will let you know. In the meantime you might consider committing a pull request

**Comment by f3dm76** [comment]
Hey @feveral , I'm glad to inform you that PR which fixed your issue (https://github.com/exyte/ActivityIndicatorView/pull/17) is currently in new version 0.0.7, you are most welcome to check it out. Have a wonderful day!
