### ISSUE TITLE
Border weight for circular views

### ISSUE THREAD

**Issue by GoodluckH** [exyte/ActivityIndicatorView#20]
I was wondering if there's a way to modify the "thickness" of some of the circular loaders? 
Thank you!

**Comment by f3dm76** [comment]
Hey @GoodluckH, I am extremely sorry for this super late response. But I am happy to tell you that I've added a number of parameters to different indicators, including width, thank you very much for your suggestion. Please check out version 1.1.0. Have an excellent day!

**Comment by GoodluckH** [comment]
Hi, @f3dm76 No worries! Thank you for adding new parameters. I'm sure they'll look awesome.
