### ISSUE TITLE
I want to make modal loading.

### ISSUE THREAD

**Issue by AngelDev0329** [exyte/ActivityIndicatorView#21]
I want to make modal loading using this.
Could you guide me to make this?

Thank you

**Comment by f3dm76** [comment]
Hey @AngelDev727, what is a modal loading? Can you please provide more details?

**Comment by AngelDev0329** [comment]
![simulator_screenshot_35FCF3AA-0277-4EDD-93E0-1BD965E5FBAF](https://user-images.githubusercontent.com/54489723/214654119-bdeaa8fc-95d0-455c-9b9a-59ae1f44e488.png)


I meant this ActivityIndicator on modal view.

**Comment by f3dm76** [comment]
Have you tried using a .sheet and displaying your activity indicator there?

**Comment by AngelDev0329** [comment]
No, I haven't tried using .sheet

**Comment by zooxop** [comment]
Hi, @AngelDev727 :)

I think you can make simply using `ZStack` and additional View components the `modal` screen you want.
Here’s an simple example that I’m using in a field project.

**Comment by zooxop** [comment]
Hi, @AngelDev727 :)

I think you can make simply using `ZStack` and additional View components the `modal` screen you want.
Here’s an simple example that I’m using in a field project.

```swift
import SwiftUI
import ActivityIndicatorView

struct ContentView: View {
    @State private var isVisible = false
    
    var body: some View {
        ZStack {
            VStack {
                Button {
                    self.isVisible.toggle()
                } label: {
                    Text("Modal On/Off")
                }
            }
            .padding()
            
            VStack {
                ZStack {
                    RoundedRectangle(cornerRadius: 20)
                        .fill(Color.white)
                        .frame(width: 100, height: 100)
                        
                    ActivityIndicatorView(isVisible: $isVisible, type: .default())
                        .frame(width: 50.0, height: 50.0)
                        .foregroundColor(Color.blue)
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.gray.opacity(0.3))
            .ignoresSafeArea()  // need iOS 14.0 later
            .isHidden(!isVisible)
            .onTapGesture {
                self.isVisible.toggle()
            }
        }
    }
}

extension View {
    @ViewBuilder func isHidden(_ isHidden: Bool) -> some View {
        if isHidden {
            self.hidden()
        } else {
            self
        }
    }
}
```

<img width="382" alt="image" src="https://user-images.githubusercontent.com/13725729/218245103-7aceea0b-6d0f-4f55-852e-a34c70b8f960.png">

 I hope it can help you.

have a good day. :)

**Comment by AngelDev0329** [comment]
It works as well.
Thank you
