### ISSUE TITLE
Want to show in specific view

### ISSUE THREAD

**Issue by tiwari1amrit** [exyte/ActivityIndicatorView#23]
Hi there,
I want to show indicator on a specific view. Is there any possibility to show in particular view?

**Comment by mixdesign** [comment]
@tiwariammit use `.overlay` modifier.

For example you could put in above the green circle:

```swift
Circle()
      .fill(.green)
      .frame(width: 32, height: 32)
      .overlay {
          ActivityIndicatorView(isVisible: $isLoading,
                                type: .gradient([.clear, .black], lineWidth: 1.84))
              .frame(width: 17.0, height: 17.0)
      }
```

**Comment by f3dm76** [comment]
Hey @tiwariammit, ActivityIndicatorView is just a `View`, you can use as you would any other SwiftUI `View`

**Comment by tiwari1amrit** [comment]
How can I add in UIKit?
