### ISSUE TITLE
when navigate to another screen while Indicator is active, it is become very fast like crazy 

### ISSUE THREAD

**Issue by michelleKaneen** [exyte/ActivityIndicatorView#26]
<img width="614" alt="Screen Shot 2024-03-11 at 2 31 23 AM" src="https://github.com/exyte/ActivityIndicatorView/assets/155519871/1b6735c2-7fcf-4404-ac81-20452b953149">

https://github.com/exyte/ActivityIndicatorView/assets/155519871/41ece4ec-e1a1-4042-98ff-45e306525d76

**Comment by SavvaShuli3v** [comment]
Same situation. 
Easy reproduce the bug with tabbar.

**Comment by f3dm76** [comment]
Hey @michelleKaneen, sorry, but I don't get it: the title is about navigation, but there is no navigation in your code. Where is the indicator during the navigation? How can you see it if you navigate away? Please attach a minimal compilable example (code, not picture) and make sure the issue reproduces on this minimal example. Have a nice day

Hey @SavvaShuli3v, please attach a minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day

**Comment by michelleKaneen** [comment]
@f3dm76 
navigation is passed within "action?()" closure, in the button directly

I was trying to make reusable button with indicator view, it seems the problem due to onAppear function 

I fixed this one by stoping the animation before executing the action?() closure
