### ISSUE TITLE
Some animations not animating

### ISSUE THREAD

**Issue by lepolt** [exyte/ActivityIndicatorView#3]
I ran the sample project, but not all the animations are working like in your demo animation: 
![Apr-25-2020 21-55-22](https://user-images.githubusercontent.com/669410/80295279-a76f4c80-873f-11ea-9e9c-3691a3a06ea6.gif)

I did a pod install in the Example directory and ran the project... but as you can see, not everything is animating.

**Comment by f3dm76** [comment]
@lepolt Thank you for bringing this to our attention! Fixed this in new pod version 0.0.2, check it out
