### ISSUE TITLE
Example project isn't working on Xcode 11.5

### ISSUE THREAD

**Issue by aaronbrethorst** [exyte/ActivityIndicatorView#4]
1. Download project
2. navigate to `Example` in terminal
3. `pod install`

expected: a workspace is generated.
actual: nothing happens.

**Comment by f3dm76** [comment]
Hello @aaronbrethorst , could you please share a console output log of pod installation attempt? Do other pods install alright for you? Do you have the latest cocoapods version? It seems to work ok for me.

**Comment by f3dm76** [comment]
Hey @aaronbrethorst , a lot of time passed, so I'm assuming the issue is resolved, please let me know if you are still having trouble. By the way, you may now use SPM for this library.
