### ISSUE TITLE
More rounded

### ISSUE THREAD

**Issue by L1cardo** [exyte/ActivityIndicatorView#5]
Is it possible to make it more rounded here ?
![image](https://user-images.githubusercontent.com/33802186/85200458-20e37f80-b32a-11ea-993d-5f100fc84ab3.png)

**Comment by f3dm76** [comment]
Hey @L1cardo , I know it's been a while, sorry about that, but I am glad to say, we've added a parameter to control stroke butt style. It's currently in master branch, but will be included in next release, have a great day!

**Comment by f3dm76** [comment]
Version 0.0.5 is out, you are most welcome to check it out, have a nice day!
