### ISSUE TITLE
Build failure in Xcode 12

### ISSUE THREAD

**Issue by ghost** [exyte/ActivityIndicatorView#6]
`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

![image](https://user-images.githubusercontent.com/47587402/85341768-522b9d80-b52c-11ea-91cc-11f791a73128.png)

**Comment by f3dm76** [comment]
Hello @golangnext, fixed the issue, please check out version 0.0.3, have a great day!
