### ISSUE TITLE
how to make a modal loading?

### ISSUE THREAD

**Issue by samma835** [exyte/ActivityIndicatorView#9]
best with a mask in background

**Comment by f3dm76** [comment]
Sorry @bullda , I do not understand what you mean, could you please elaborate? What is a modal loading, and where do you want the mask to be?

**Comment by f3dm76** [comment]
Hey @bullda, do you still need help with this? Could you please provide more details if you do? Or may I close this issue?

**Comment by f3dm76** [comment]
Closing this one for now, since I don't understand what needs to be done
